root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server/main.go"
  bin = "./tmp/server"
  delay = 1000
  exclude_dir = ["tmp", "migrations"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go"]
  kill_delay = 500

[log]
  time = false
