CREATE TABLE IF NOT EXISTS balances (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    amount BIGINT NOT NULL DEFAULT 0,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
